travis:
  secure:
    BINSTAR_TOKEN: M+efVhys0ZHi346wZAblevXc6mTStjPaSOqybaN3Zm/eEzJW611C7quCswKBOwfqeYhqhF3XiDnboNBK6jjOn52nvhtP/+cLaJby9sqiL0w6DFHDJ2Y8EI1BZJkU8qSyGcFvfeqoKDEZGvQKr8SgVLvdy1uHc0Rra5dSI+xTwtymdcLR+vWPitbszp6i+wYZCi+77QOx5Va/9w3KohfEsO2xRe7NxcaDJiOwifgJ8OSVv8ZWrTuGVVRXYMOJ4Ep8x5jZentYEDyZB0O1mmZEUL0lHeY9pQjeYMJ9+1zlI3yMEWWalAr0wjxg6vWW1XpdSvUJj1NbO5lyJ4ZZfivG1IQ8QzK/RUAWZI2Jh1jbjMyuhK/ysX4YWI/d49/zUqXho/O18eRnzuBgWSot3i+3+KhkIPt1DqKRZikkxkyPmNJMCDisMsFlZIVuUsvpxzANyh653jFTIMNTJQS7ItQ5FX5H7VjM5uMVfUjLAkREJidTNa66H9qKQe6Vav1s+fxKgsIJWBf6XR9GeGbMQQTwSsr8ZRgTlZJmeYLQJk4Tg5PLulavmJBkjKidgGs+MdyrvitXLOmzrp5Fiy6m8eOoeH2rKiSg7xPOXC/ww2jSNoobk/1wR5Qp47dsMQrVEGMhGorzm8p3j/ncCDSdGvPHSc+XRPaS447jIb4pYB7Mo/U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
