travis:
  secure:
    BINSTAR_TOKEN: R+M65QuV4PUaTGDj1iAv+lPOXw6qtUxTiXJk0oY2ZeQdNy6K7O+UgnmmxUUHAHKfvgwPGDys0F9PRRpsoQYP6g/EZxKmRZVN6gnjsLlKzRKC6iFJ1I116ct2ohoJg1TIt7OTcDsAhuBxSr5af/SClcPyEBRuSohVrwo17wbemxNgZXNLYCnvc5FX0/h8qZBDOtmGkY32ocSIxTlIE8ef9qpfSycn30RQQCNY2dKaEXIY3z/bn4ngA6EgLDGOfPwTXer3f3hc5+Wpfqc3Qk4URq1EWRmkls/vgdLUYcLmP1frLaYCOKI/LjK6hfZqMZVpiE+g9NPke+uPN4VOBSCH7HMsrDd+mEtLWFgstWsZjx2LEbJ5P6ZDieslZ9Fft/81yu48nqbGQDAQ6Yrm9aAdwndhHai+B37JkFQ8YzlNF/ZlSkq9fm7V10cEBNzB5P7K26OUYzbNygo1X7g49x5bqC5oRkHfejUwPk8i7q4n7QfA+phGsOu0zkad6riq0D8D0ZQu1y7MNhxcXJMlf1aJ/NEtMNHzEWt/BgF0ijrm61REcbXqcQQeAe2HBy4tGozNmh0gqEwc5J8U8hkM/a9YR7DYBatETlFp71wc8xTNy0XV1QaTyfruIADKfqxBxsQTLZaxRjKoIYBXj9iBdP0nf+0andpXo+Vbv2clcE7qA2w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
